############################### Cover ############################### > start
cover:

  title: WBW's Blog
  subtitle: Personal Website of Bowen Wang
  features:
    - name: GitHub
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f389.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f389.svg
      url: https://github.com/wbw625/
    - name: 博客
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f4f0.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4f0.svg
      url: /archives/
    - name: 源码
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f9ec.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f9ec.svg
      url: https://github.com/wbw625/try_hexo


############################### Sidebar ############################### > start
sidebar:
  widget_library:
    blogger:
      url: /
      social:
        - icon: fa-solid fa-rss
          url: tel:13915237083
        - icon: fa-solid fa-envelope
          url: mailto:625114674@sjtu.edu.cn
        - icon: fab fa-github
          url: https://github.com/wbw625/
        - icon: fa-solid fa-headphones-alt
          url: https://space.bilibili.com/1683525074


############################### Site Footer ############################### > start
site_footer:
  # layout of footer: [aplayer, social, license, info, copyright]
  # layout: [aplayer, social, license, analytics, info, copyright]
  layout: [info, copyright]
  social:
    - icon: #fa-solid fa-rss
      url:
    # or
    - img:
      url:
    # or
    - avatar:
      url:
  # site source
  source: https://github.com/wbw625/wbw625.github.io
  # analytics using leancloud
  analytics: >
    <span id="lc-sv">本站总访问量为 <span id='number'><i class="fa-solid fa-loader fa-spin fa-fw" aria-hidden="true"></i></span> 次</span>
    <span id="lc-uv">访客数为 <span id='number'><i class="fa-solid fa-loader fa-spin fa-fw" aria-hidden="true"></i></span> 人</span>
  # site copyright
  copyright: '[Copyright © since 2025 wbw625](/)'
  # You can add your own property here. (Support markdown, for example: br: '<br>')
  br: '<br>'


############################### Navigation Bar ############################### > start
# 注意事项：建议规范全站路径 URL 最后带一个 "/" 例如 "about/"
navbar:
  visiable: auto # always, auto
  logo: # choose [img] or [icon + title]
    img: volantis-static/media/org.volantis/blog/Logo-NavBar@3x.png # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/Logo-NavBar@3x.png
    icon:
    title:
  menu:
    - name: 首页
      icon: fa-solid fa-rss
      url: /
    # - name: 分类
    #   icon: fa-solid fa-folder-open
    #   url: categories/
    # - name: 标签
    #   icon: fa-solid fa-tags
    #   url: tags/
    - name: 归档
      icon: fa-solid fa-archive
      url: archives/
    - name: 关于
      icon: fa-solid fa-info-circle
      url: https://github.com/wbw625/
  search: Search...   # Search bar placeholder


############################### Article Layout ############################### > start
# 文章布局
article:
  body:
    footer_widget:
      # 版权声明组件 (for layout: post)
      copyright:
        enable: true
        custom: true # 开启后替代上方内容的版权显示
        customData:
          default: type2  # 默认授权声明

    meta_library:
      # 默认文章作者（可在 _data/author.yaml 中增加其他作者，并在 front-matter 中设置）
      # https://volantis.js.org/advanced-settings/#多人协同
      author:
        avatar: volantis-static/media/org.volantis/blog/favicon/apple-touch-icon.png # https://cdn.jsdelivr.net/gh/volantis-x/cdn-org/blog/favicon/apple-touch-icon.png
        name: Bowen Wang
        url: https://github.com/wbw625/


plugins:
  parallax:
    enable: true
