############################### Cover ############################### > start
cover:

  title: WBW's Blog
  subtitle: Personal Website of Bowen Wang
  features:
    - name: GitHub
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f389.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f389.svg
      url: https://github.com/wbw625/
    - name: 博客
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f4f0.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f4f0.svg
      url: /archives/
    - name: 源码
      icon: #
      img: volantis-static/media/twemoji/assets/svg/1f9ec.svg #  https://cdn.jsdelivr.net/gh/twitter/twemoji@13.0/assets/svg/1f9ec.svg
      url: https://github.com/wbw625/try_hexo


############################### Sidebar ############################### > start
sidebar:
  widget_library:
    blogger:
      url: /
      social:
        - icon: fa-solid fa-rss
          url: tel:13915237083
        - icon: fa-solid fa-envelope
          url: mailto:625114674@sjtu.edu.cn
        - icon: fab fa-github
          url: https://github.com/wbw625/
        - icon: fa-solid fa-headphones-alt
          url: https://space.bilibili.com/1683525074


plugins:
  parallax:
    enable: true
